DashboardSella/Controllers/ImageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sella_DashBoard.Models;
using System.Text.Json;

namespace DashboardSella.Controllers
{
    [Authorize]
    public class ImageController : Controller
    {
        IWebHostEnvironment hostingEnvironment;
        HttpClient client = new HttpClient();
        string route = "http://localhost:49182/api/Image";
        string route1 = "http://localhost:49182/api/Product";
        public ImageController(IWebHostEnvironment _hostingEnvironment)
        {

        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Images> Imgs = await client.GetFromJsonAsync<List<Images>>(route);
            List<Product> P = await client.GetFromJsonAsync<List<Product>>(route1);
            ViewBag.products = new SelectList(P, "ProductID", "ProductName", 1);
            return View(Imgs);
        }

        //[HttpGet]
        //public async Task<IActionResult> Search(int? products)
        //{
        //    if (products > 0)
        //    {
        //        List<Images> Imgs = await client.GetFromJsonAsync<List<Images>>($"http://localhost:49182/api/Image/product/{products}");
        //        List<Product> P = await client.GetFromJsonAsync<List<Product>>(route1);
        //        ViewBag.products = new SelectList(P, "ProductID", "ProductName", 1);
        //        return View("Index", Imgs);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index");
        //    }

        //}

        public async Task<IActionResult> Search(int? products)
        {
            if (products > 0)
            {
                try
                {
                    List<Images> Imgs = await client.GetFromJsonAsync<List<Images>>($"http://localhost:49182/api/Image/filter/{products}");

                    List<Product> P = await client.GetFromJsonAsync<List<Product>>(route1);
                    ViewBag.products = new SelectList(P, "ProductID", "ProductName", 1);
                    return View("Index", Imgs);
                }
                catch (JsonException ex)
                {
                    // Handle JSON deserialization error
                    return BadRequest("Invalid JSON format: " + ex.Message);
                }
                catch (HttpRequestException ex)
                {
                    // Handle HTTP request error
                    return BadRequest("Error retrieving data from server: " + ex.Message);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            List<Product> P = await client.GetFromJsonAsync<List<Product>>(route1);
            ViewBag.products = new SelectList(P, "ProductID", "ProductName", 1);
            return View();

        }

        public async Task<IActionResult> Create([FromForm] ProductImagesDTO data)
        {
            // Create a new MultipartFormDataContent object to hold the request body
            var content = new MultipartFormDataContent();

            // Add the product ID to the request body
            content.Add(new StringContent(data.ProductID.ToString()), "ProductID");

            // Loop through the uploaded images and add them to the request body
            if (data.ImageURL != null && data.ImageURL.Count > 0)
            {
                foreach (var image in data.ImageURL)
                {
                    // Add the image file to the request body
                    byte[] fileBytes;
                    using (var memoryStream = new MemoryStream())
                    {
                        await image.CopyToAsync(memoryStream);
                        fileBytes = memoryStream.ToArray();
                    }

                    content.Add(new ByteArrayContent(fileBytes), "ImageURL", image.FileName);
                }
            }

            // Create a new HttpClient object and set its base address to the API's URL
            var apiUrl = "http://localhost:49182";
            var client = new HttpClient { BaseAddress = new Uri(apiUrl) };

            // Create a new HttpRequestMessage object with the POST method and the request body
            var request = new HttpRequestMessage(HttpMethod.Post, "/api/Image");
            request.Content = content;

            // Send the request using the HttpClient object and wait for the response
            var response = await client.SendAsync(request);

            // Check the status code of the response and return a result
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            Images Img = await client.GetFromJsonAsync<Images>(route + "/" + id);
            List<Product> P = await client.GetFromJsonAsync<List<Product>>(route1);
            ViewBag.products = new SelectList(P, "ProductID", "ProductName", 1);
            return View(Img);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [FromForm] ProductImagesDTO data)
        {
            var content = new MultipartFormDataContent();

            // Add the product ID to the request body
            content.Add(new StringContent(data.ProductID.ToString()), "ProductID");

            // Loop through the uploaded images and add them to the request body
            if (data.ImageURL != null && data.ImageURL.Count > 0)
            {
                foreach (var image in data.ImageURL)
                {
                    // Add the image file to the request body
                    byte[] fileBytes;
                    using (var memoryStream = new MemoryStream())
                    {
                        await image.CopyToAsync(memoryStream);
                        fileBytes = memoryStream.ToArray();
                    }

                    content.Add(new ByteArrayContent(fileBytes), "ImageURL", image.FileName);
                }
            }

            // Create a new HttpClient object and set its base address to the API's URL
            var apiUrl = "http://localhost:49182";
            var client = new HttpClient { BaseAddress = new Uri(apiUrl) };

            // Create a new HttpRequestMessage object with the POST method and the request body
            var request = new HttpRequestMessage(HttpMethod.Put, $"/api/Image/{id}");
            request.Content = content;

            // Send the request using the HttpClient object and wait for the response
            var response = await client.SendAsync(request);

            // Check the status code of the response and return a result
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {

            Images Img = await client.GetFromJsonAsync<Images>(route + "/" + id);
            return View(Img);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            Images Img = await client.GetFromJsonAsync<Images>(route + "/" + id);
            return View(Img);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await client.DeleteAsync(route + "/" + id);
            return RedirectToAction("Index");
        }
    }
}

DashboardSella/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sella_DashBoard.Models;
using PagedList.Mvc;
using PagedList;
using Microsoft.AspNetCore.Authorization;

namespace DashboardSella.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        HttpClient client = new HttpClient();
        string route = "http://localhost:49182/api/Product";
        string route1 = "http://localhost:49182/api/Category";
        string route2 = "http://localhost:49182/api/Image/product";

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            List<Product> Products = await client.GetFromJsonAsync<List<Product>>(route);
            return View(Products);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {

            List<Category> categories = await client.GetFromJsonAsync<List<Category>>(route1);
            ViewBag.country = new SelectList(categories, "CategoryID", "CategoryName", 1);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            HttpResponseMessage httpResponse = await client.PostAsJsonAsync<Product>(route, product);
            if (httpResponse.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            List<Category> categories = await client.GetFromJsonAsync<List<Category>>(route1);
            ViewBag.country = new SelectList(categories, "CategoryID", "CategoryName", 1);
            Product P = await client.GetFromJsonAsync<Product>(route + "/" + id);
            return View(P);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Product P)
        {
            HttpResponseMessage httpResponse = await client.PutAsJsonAsync<Product>(route + "/" + id, P);
            if (httpResponse.StatusCode == System.Net.HttpStatusCode.OK)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {

            List<string> _imageUrl = new List<string>();
            List<Images> _images = await client.GetFromJsonAsync<List<Images>>(route2 + "/" + id);
            Product P = await client.GetFromJsonAsync<Product>(route + "/" + id);
            foreach (var _img in _images)
            {
                _imageUrl.Add(_img.ImageURL);
            }
            var viewModel = new ProductDetailsViewModel
            {
                Images = _imageUrl,
                Products = P
            };
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            Product P = await client.GetFromJsonAsync<Product>(route + "/" + id);
            return View(P);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await client.DeleteAsync(route + "/" + id);
            return RedirectToAction("Index");
        }

    }
}

DashboardSella/Controllers/UserController.cs
using DashboardSella.Data;
using DashboardSella.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DashboardSella.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;


        public UserController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {

            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                user.Email = roles.FirstOrDefault();
            }
            return View(users);
        }

        public async Task<IActionResult> ResetPassword(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var resetToken = await _userManager.GeneratePasswordResetTokenAsync(user);
            var model = new ResetPasswordViewModel
            {
                UserId = user.Id,
                ResetToken = resetToken,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.ResetPasswordAsync(user, model.ResetToken, model.NewPassword);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(IdentityUser user)
        {
            if (ModelState.IsValid)
            {
                var existingUser = await _userManager.FindByIdAsync(user.Id);
                if (existingUser == null)
                {
                    return NotFound();
                }

                existingUser.UserName = user.UserName;
                existingUser.Email = user.Email;

                var roles = await _userManager.GetRolesAsync(existingUser);
                var result = await _userManager.RemoveFromRolesAsync(existingUser, roles);
                if (result.Succeeded)
                {
                    result = await _userManager.AddToRoleAsync(existingUser, user.Email);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(user);
        }
        public async Task<IActionResult> Edit(string id)
        {

            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            user.Email = roles.FirstOrDefault();
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View("Index", await _userManager.Users.ToListAsync());
        }

    }
}

DashboardSella/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DashboardSella.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/x-icon" href="~/SLogo.ico" />

</head>
<body>
    @if (SignInManager.IsSignedIn(User))
    { 
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">Sella</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Index">Product Image</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Accounts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Reports</a>
                            </li>
                    </ul>
                    <partial name="_LoginPartial" />
                      
                </div>
            </div>
        </nav>
    </header>
    }
    else{
       @* <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sella</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">       
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>*@
        <br />
        <br />
        <br />
        <br />
       
        
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <partial name="_LoginPartial" />
        </div>

       
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DashboardSella - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.35.5/apexcharts.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>